"""empty message

Revision ID: 33f66c0e6acf
Revises: 282b3d02ef25
Create Date: 2025-01-20 22:47:24.452660

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33f66c0e6acf'
down_revision = '282b3d02ef25'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recipe_ingredient',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parent_recipe_id', sa.Integer(), nullable=False),
    sa.Column('sub_recipe_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=True),
    sa.Column('unit', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['parent_recipe_id'], ['recipe.id'], ),
    sa.ForeignKeyConstraint(['sub_recipe_id'], ['recipe.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recipe_ingredient')
    # ### end Alembic commands ###
