services:
  - type: web
    name: kitchen-companion
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn 'app:create_app()' --bind=0.0.0.0:$PORT
    envVars:
      - key: FLASK_APP
        value: app
      - key: FLASK_ENV
        value: production