"""Add fraction support and custom section ordering

Revision ID: 05120dfd4042
Revises: 1afe6a3a794c
Create Date: 2025-03-06 17:19:14.152218

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05120dfd4042'
down_revision = '1afe6a3a794c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ingredient_section', schema=None) as batch_op:
        batch_op.add_column(sa.Column('order', sa.Integer(), nullable=True))

    with op.batch_alter_table('recipe_ingredient', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quantity_numerator', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('quantity_denominator', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('is_fraction', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipe_ingredient', schema=None) as batch_op:
        batch_op.drop_column('is_fraction')
        batch_op.drop_column('quantity_denominator')
        batch_op.drop_column('quantity_numerator')

    with op.batch_alter_table('ingredient_section', schema=None) as batch_op:
        batch_op.drop_column('order')

    # ### end Alembic commands ###
