"""Fix IngredientSection table references

Revision ID: ce177499f19a
Revises: d8a62822fdf2
Create Date: 2025-01-19 16:43:00.711121

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce177499f19a'
down_revision = 'd8a62822fdf2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ingredient_section', schema=None) as batch_op:
        batch_op.alter_column('section_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ingredient_section', schema=None) as batch_op:
        batch_op.alter_column('section_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
