"""Fix ingredient_section relationship

Revision ID: d8a62822fdf2
Revises: fafc44cda4af
Create Date: 2025-01-15 15:58:42.725657

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8a62822fdf2'
down_revision = 'fafc44cda4af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ingredient', schema=None) as batch_op:
        batch_op.drop_column('weekly_plan_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ingredient', schema=None) as batch_op:
        batch_op.add_column(sa.Column('weekly_plan_id', sa.INTEGER(), nullable=True))

    # ### end Alembic commands ###
