"""Add USDA fields to ingredients

Revision ID: d95c6ff880e3
Revises: 05120dfd4042
Create Date: 2025-03-20 16:18:09.093866

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd95c6ff880e3'
down_revision = '05120dfd4042'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ingredient', schema=None) as batch_op:
        batch_op.add_column(sa.Column('usda_fdc_id', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('is_custom', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('display_name', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('category', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ingredient', schema=None) as batch_op:
        batch_op.drop_column('category')
        batch_op.drop_column('display_name')
        batch_op.drop_column('is_custom')
        batch_op.drop_column('usda_fdc_id')

    # ### end Alembic commands ###
